### ISSUE TITLE
Figure out if we can do a diff between the old CRO file and the current CRO file

### ISSUE THREAD

**Issue by nicolevasilevsky** [data2health/architecting_attribution#10]
@marijane, if it is not easy to do this automatically, I can do it manually.

**Comment by nicolevasilevsky** [comment]
from our notes, @marijane is meant to look into doing a ROBOT diff on the labels from the original CRO and the current CRO

**Comment by nicolevasilevsky** [comment]
here is a list of terms that are in the original contribution ontology, but are not in CRO:
https://docs.google.com/spreadsheets/d/1-TrSX4va26XEOQofeSzwmJ6w_c1MG0iKDZnJkToElyc/edit#gid=0

There are 39 terms that are not in CRO that are in the contribution ontology

**Comment by nicolevasilevsky** [comment]
reassigning to @kristiholmes to review and assign next steps

**Comment by kristiholmes** [comment]
awesome, thank you very much!  I will be able to take a look at this on Thurs.

**Comment by nicolevasilevsky** [comment]
are there any next steps for this ticket?

**Comment by marijane** [comment]
No.  We moved it to Done in the sprint planning board, and it kind of overlaps with the ticket about pulling in the workshop terms (which I recall were the source for the terms in the OpenRIF CRO) so I'll go ahead and close it.
