### ISSUE TITLE
decide if we want to add additional classes to CRO from the Force2015 workshop

### ISSUE THREAD

**Issue by nicolevasilevsky** [data2health/architecting_attribution#11]
this spreadsheet contains all of the terms that were brainstormed at the Force2015 workshop:
https://docs.google.com/spreadsheets/d/1BudaIWSIgo7RVmzIpWO_hkE5mlgeii16xBTY37d0Zek/edit#gid=0

At the F2F, we decided that we didn't want to add all of these terms to the CRO at this time. I think a lot of terms are overlapping though, is it worth comparing this file to to the terms that are currently in the CRO, to see if there are some new terms we may want to potentially add?

**Comment by LisaOKeefe1** [comment]
Kristi looking at it now. Will complete in sprint starting 4/11/19.

**Comment by LisaOKeefe1** [comment]
https://docs.google.com/spreadsheets/d/1-TrSX4va26XEOQofeSzwmJ6w_c1MG0iKDZnJkToElyc/edit#gid=0

**Comment by nicolevasilevsky** [comment]
@LisaOKeefe1 what is the action item here?

**Comment by LisaOKeefe1** [comment]
@nicolevasilevsky replied in Slack. @kristiholmes will be taking a look.

**Comment by kristiholmes** [comment]
philosophical question here - do we want to include roles that people ARE or only roles that they DO? I'm thinking inventor, librarian, and project manager role might be a good fit, but each one of these "roles" are DOING the concepts already included in the CRO. 

What do you think?

I'd suggest that we release AS-IS and then dig into this a bit more once we see how people use it.
@nicolevasilevsky @marijane @LisaOKeefe1
