### ISSUE TITLE
edit the readme at the new CRO to point back at the old one

### ISSUE THREAD

**Issue by nicolevasilevsky** [data2health/architecting_attribution#13]
and add some citations to relevant papers and posters

**Comment by nicolevasilevsky** [comment]
@marijane is this still something you want to do, or should we close this?

**Comment by marijane** [comment]
We still need to do this.  I will try to do it today.

**Comment by nicolevasilevsky** [comment]
I added a new section with publications and other scholarly products related to this project: https://github.com/data2health/contributor-role-ontology/blob/master/README.md 

Closing this ticket, but feel free to add any additional content if needed.
