### ISSUE TITLE
Create an example of the annotation file structure (v.1)

### ISSUE THREAD

**Issue by nicolevasilevsky** [data2health/architecting_attribution#14]
Draft annotation file structure is here:
https://docs.google.com/spreadsheets/d/1sqDi2RtErDUqP1ovyV45Cz07vYvxnpyOjwBVJt2k3a8/edit#gid=0

**Comment by LisaOKeefe1** [comment]
Put out for comments .

**Comment by nicolevasilevsky** [comment]
I think the draft of this annotation file structure looks fine, although we need to decide how we'll annotate the research outputs, this is not clear to me.

**Comment by LisaOKeefe1** [comment]
@nicolevasilevsky thanks. Should we open a story (ticket) for that? I'm happy to do it and you can fill in whatever color you think will help. Just lmn.  Ty!

**Comment by nicolevasilevsky** [comment]
I think this is covered by #34
