### ISSUE TITLE
Documentation of diverse use cases

### ISSUE THREAD

**Issue by mellybelly** [data2health/architecting_attribution#16]
We need to illustrate: contributions to different types of research products, and their representation in the file. The use cases could also include what viewing that information might look like (for example, in a software repo there could be a file analogous to the license.md file).

**Comment by mellybelly** [comment]
@mbrush or @kristiholmes - this can be from the model documentation and in the guidebook- dual purpose?

**Comment by mellybelly** [comment]
e.g we want the union of them in both places ;-)

**Comment by kristiholmes** [comment]
Per discussions with the group, it was decided that a deep dive into research objects was out of scope at this time. A light-weight discussion is included in the guidebook.
