### ISSUE TITLE
refactor ROO to RAO

### ISSUE THREAD

**Issue by nicolevasilevsky** [data2health/architecting_attribution#20]
rename ROO to research artefact ontology (RAO)

**Comment by nicolevasilevsky** [comment]
Can this be closed? I don't think we are creating ROO/RAO anymore, right?

**Comment by marijane** [comment]
Not yet.  One of my tasks (#34) for the current sprint is to write down all our thoughts about whether an ontology is needed.  If we decide no, then this can be closed, but if we decide yes, we would still want to do this eventually.

**Comment by nicolevasilevsky** [comment]
Got it, thanks for clarifying!

**Comment by kristiholmes** [comment]
hello, just going through issues - what do you think about closing? Especially with the work happening to push the COAR resource types to wikidata? Thanks!  @marijane @nicolevasilevsky

**Comment by nicolevasilevsky** [comment]
yes, let's close
