### ISSUE TITLE
Scope demonstrator application project

### ISSUE THREAD

**Issue by kristiholmes** [data2health/architecting_attribution#23]
**Develop wizard to generate enhanced attribution content.** Input could be a persistent identifier (or set of PIDs), output is properly formatted citation with enhanced content or block of text.

- narrative for contributions to science sections of the biosketch
- annotations for individual citations (e.g., [critical references form](https://www.feinberg.northwestern.edu/fao/docs/admin-promo-tenure/Dossier-Critical-References-Form.doc) or a CV)

**To determine:** deliverables, staffing, schedule, stakeholders, CTSA context, communication plan

**Comment by nicolevasilevsky** [comment]
@kristiholmes the link to the critical references form does not work for me

**Comment by nicolevasilevsky** [comment]
I had another idea of a way people could use the CRO to annotate their CV - I have a personal website that lists my publications, and I could annotate my contributions to papers, projects, etc, using the CRO - I created an example with the first pub on my list here: https://nicolevasilevsky.github.io/publications/

**Comment by nicolevasilevsky** [comment]
One open question I have is how are folks to use the CRO? In the example above, I linked to the CRO in OLS, but that is not what we'd expect people to do in reality. Would the CRO be just a source of labels/terms on their CV? Or would the identifiers be referenced/linked somehow?

**Comment by LisaOKeefe1** [comment]
> @kristiholmes the link to the critical references form does not work for me

Hi there. It is broken for me, too.

**Comment by kristiholmes** [comment]
Hi - I think it is behind the firewall.  Sorry about that. See [NU Team Scientists page](https://www.feinberg.northwestern.edu/fao/for-administrators/team-scientists/index.html) for more information (click to download the Guide for Appointments, Promotion and Tenure (PDF)).

**Comment by nicolevasilevsky** [comment]
what are the specific action items for this ticket? @kristiholmes should you, me and @eichmann meet to discuss this?

**Comment by kristiholmes** [comment]
that sounds terrific, thanks.

**Comment by nicolevasilevsky** [comment]
Could we add this to our agenda for our Thurs call, or do we need a separate call for this?

**Comment by LisaOKeefe1** [comment]
https://docs.google.com/spreadsheets/d/1feSeHrBBGD2Q7kLyq5vCGlQJztgPu1f-7P-XwICznwI/edit#gid=0

**Comment by LisaOKeefe1** [comment]
Per our sprint planning meeting on 4/11, we will schedule time with Dave Eichmann to discuss demo requirements a bit more. Note that this still might be something created during a Hack-event.

**Comment by LisaOKeefe1** [comment]
@kristiholmes  and @eichmann thanks for meeting today. Based on our conversation here is the next thing we need to do. Will add more open items shortly, so we can turn them into stories if needed. 
- [ ] decide what we want to use as our source (Scopus, Pubmed Central, DOI through CrossRef, other?)

**Comment by LisaOKeefe1** [comment]
Just saving the user story for this here: "As a transitional scholar I want to be able to enter to annotate my list of contribution roles and have it returned i a way so I can use it as a guide to write my personal framework, augment my CV, or show hub impact. "

**Comment by kristiholmes** [comment]
Let's table this for a while until we get a better idea of what to do...
