### ISSUE TITLE
Investigate "object type" data models (e.g. vocabularies/taxonomies)

### ISSUE THREAD

**Issue by kristiholmes** [data2health/architecting_attribution#27]
Some of the suggestions include MeSH publication types, wikidata, etc.
MJ looking for what's available in RDF. :-)

Overall Qs to resolve:

- is it our goal to use linked data?
- what are our requirements?
- What makes it useful?

**Comment by mellybelly** [comment]
The requirements I know of thus far are:
1) search faceting 
2) alignment with upper level types within our discovery index
3) typing of contribution artifacts (presume they can be multiply-typed?)

It would be good to serve up the data in multiple ways, lets make a separate ticket for the sci-platform for this purpose.

It might be a good idea to have a requirements document in this repo to further describe the needs with examples of how they would work.

**Comment by diatomsRcool** [comment]
Also look at [CRediT](https://dictionary.casrai.org/Category:Objects) and [TaDiRAH](http://tadirah.dariah.eu/vocab/index.php). There are loads of vocabularies for this.

**Comment by marijane** [comment]
Thank you, @diatomsRcool !

**Comment by mellybelly** [comment]
@marijane has an ontological version of CRediT linked herein (we were contributors) but i had not seen TaDiRAH, cool!

**Comment by marijane** [comment]
@mellybelly Anne's CRediT link is actually a link to the CASRAI Objects, it's worth checking out!

**Comment by mellybelly** [comment]
yes, this is what we contributed to (it was a working group). but the end result is not computable, so that was the need for the OWL version ;-)

**Comment by kristiholmes** [comment]
CASRAI works in the context of existing research information systems, which is important for harmonizing across various systems. This also makes it easier for information systems to adopt and implement. This is one of the reasons we mapped the NISO research objects vocabulary to different existing research information system  data models (researchfish, figshare, scopus & WoS, etc.). I don't have a strong feeling about what to use, just that we use something. The NISO framework underwent significant peer review, so that is why we started there.

**Comment by kristiholmes** [comment]
@diatomsRcool have you seen any specific mappings of the CASRAI object terms to research system  data models, by chance?  I am wondering if this mapping has been completed in a systematic manner. Thanks for your suggestions!

**Comment by marijane** [comment]
@mellybelly our OWL implementation is limited to the CASRAI contributor roles, it does not cover the objects.  Did I miss something, is it supposed to include them?

**Comment by kristiholmes** [comment]
no - these are separate

**Comment by diatomsRcool** [comment]
@kristiholmes I have not, but for my work in RDA, we will/may add some of the CASRAI object terms to VIVO.

**Comment by kristiholmes** [comment]
@diatomsRcool very nice! I didnt realize there was a RDA VIVO project. Thanks again for the pointer to this vocabulary

**Comment by diatomsRcool** [comment]
It's not formal, but we are looking to form a list of terms from the community for adding to VIVO. Let me know if you have terms you want to add. We'll probably start with higher level terms first, tho.

**Comment by kristiholmes** [comment]
CASRAI - URIs
MeSH - RDF
COAR - RDF
