### ISSUE TITLE
Related Repos

### ISSUE THREAD

**Issue by kristiholmes** [data2health/architecting_attribution#3]
Is OpenRIF a related repo? https://github.com/openrif

**Comment by mellybelly** [comment]
I think so.

**Comment by nicolevasilevsky** [comment]
It is an org, not a repo. I think we should create a new header that says Related Organizations and put it under there.

**Comment by nicolevasilevsky** [comment]
Or maybe we don't need it at all? I think we included all the relevant repos under the OpenRIF org.

(Note, I just added all the related repos to the ReadMe file)

**Comment by nicolevasilevsky** [comment]
related to #7

**Comment by nicolevasilevsky** [comment]
I am closing this ticket - OpenRIF is included on our list of repos and now has a description. Please reopen if you'd like to discuss further.
