### ISSUE TITLE
Metadata workshop - make better badges

### ISSUE THREAD

**Issue by LisaOKeefe1** [data2health/architecting_attribution#32]
We should take a hint from ORD camp and make some cool badges :)

**Comment by kristiholmes** [comment]
Yes, most definitely.  I have been wanting to try this out for a conference ever since I attended SciFoo. https://badge.reviews/

**Comment by LisaOKeefe1** [comment]
Badge templates
https://github.com/BadgeReviews/badges
https://github.com/BadgeReviews/badges/blob/master/PSD/Badge-Template.psd
