### ISSUE TITLE
Work on a plan of sorts for the RAO.  

### ISSUE THREAD

**Issue by LisaOKeefe1** [data2health/architecting_attribution#34]
work on a plan of sorts for the RAO.  Enumerate use cases, carefully document all the sources for terms we’ve considered,  and evaluate ontologies for reuse. We'll break this out into user stories then.

**Comment by nicolevasilevsky** [comment]
are we still creating an RAO? I am a bit confused and out of the loop.

**Comment by marijane** [comment]
Aha!  This is the ticket I was talking about in my last comment on #20.  We need to document our rationale for creating or not creating an ontology, so it's still up in the air.  Our latest idea is to implement the CASRAI Objects in a fashion similar to the CRediT ontology, but to also map all of the various research output/object/artifact vocabularies we've been talking about (this is also part of that documentation).

**Comment by LisaOKeefe1** [comment]
yes! Is this something we need to move to this sprint @marijane ? Please let me know what makes sense for us in terms of order. Thanks!  🥇

**Comment by marijane** [comment]
Oh!  Did we break this up into smaller tasks?  I'll be able to review things in a couple hours and figure this all out.

**Comment by kristiholmes** [comment]
from: #35  Overall goal: Work to unify concepts across different systems. Brain dump will help this. Start with CASRAI, (then NISO, then COAR). Section for each vocabulary.

just adding this comment to this issue so that we have it.

**Comment by kristiholmes** [comment]
today during the sprint planning meeting, it would be helpful to spend a few minutes chatting about 

- #36 #37 and #38 and what role they play in the concept of research artifacts
- how RA are incorporated into the annotation file
- what concepts overlap with metadata discussions, such as concepts of scholarly output that we may want to represent in various platforms

@LisaOKeefe1 @nicolevasilevsky @marijane

**Comment by LisaOKeefe1** [comment]
@kristiholmes  thanks. This is great prep for us. If there is one goal that I have for us as a team today it's for us to make sure that we are clearly defining what we expect to get done in two weeks. This will definitely help us scope out the fortnight.

**Comment by kristiholmes** [comment]
we will not do a PLAN, per se. We will as a first step map MeSH publication types to wikidata, then the COAR vocabulary.
@nicolevasilevsky  @marijane @LisaOKeefe1
