### ISSUE TITLE
Investigate COAR vocabularies

### ISSUE THREAD

**Issue by kristiholmes** [data2health/architecting_attribution#38]
specifically resource types, in the context of artifacts.
https://www.coar-repositories.org/activities/repository-interoperability/coar-vocabularies/

**Comment by LisaOKeefe1** [comment]
Here's the doc should any community members wish to read, comment: https://docs.google.com/spreadsheets/d/1Mw8gK2NUGM8po7GGRtJTShRM2QNFoR19VJrjQuVCDW8/edit#gid=323661248

Please let us know if you have any questions.

**Comment by kristiholmes** [comment]
investigation complete, with 88.6% in wikidata (62/70)
