### ISSUE TITLE
Represent role attributes that can exist for research outputs as larger program or project-level roles

### ISSUE THREAD

**Issue by nicolevasilevsky** [data2health/architecting_attribution#4]
This is from the [Phase 2 doc](https://docs.google.com/document/d/1U0nzWf8rcCCEayxfc-qF0ikVEarBlZyacXu4NWK2ICQ/edit). Not entirely sure what the action item is here

**Comment by nicolevasilevsky** [comment]
@kristiholmes is there a specific action item here, or could this be closed?

**Comment by mellybelly** [comment]
I believe that this is accomplished by the new model we discussed- it provides context for the contributions; e.g. an individual contribution to a small research product, that product can be part of a larger program or project. We should make sure that the use cases, model, and documentation support this. I don't think its an ontology modeling question, but it is an annotation format question (according to current thinking).

**Comment by kristiholmes** [comment]
yes, agree - sending more info and the draft annotation file for discussion.
