### ISSUE TITLE
Plan for objects/artfacts (DRAFT)

### ISSUE THREAD

**Issue by kristiholmes** [data2health/architecting_attribution#41]
Use research objects from Wikidata for the annotation files

- Review research objects/artefacts in the [COAR Controlled Vocabularies](https://www.coar-repositories.org/activities/repository-interoperability/coar-vocabularies/) (specifically the [Resource Type Vocabulary](https://www.coar-repositories.org/activities/repository-interoperability/coar-vocabularies/deliverables/)) The COAR Controlled Vocabularies are described in SKOS. https://github.com/data2health/architecting_attribution/issues/38 
- Map these terms to Wikidata terms. (we will first review [the process for contributing to Wikidata](https://www.wikidata.org/wiki/Wikidata:Contribute)) https://github.com/data2health/architecting_attribution/issues/39 
- Consider further annotation with schema described [here](https://elifesciences.org/inside-elife/1fd1018c/research-assessment-reducing-bias-in-the-evaluation-of-researchers) (objects and activities, to be addressed later) or this list of items of translational significance [described here](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2801963/) and [shown here](https://becker.wustl.edu/impact-assessment/how-to-use), as well as [this](https://academic.oup.com/rev/article/25/3/235/2364361) and others (TBD, create new issue)
- [Draft annotation file](https://docs.google.com/spreadsheets/d/1sqDi2RtErDUqP1ovyV45Cz07vYvxnpyOjwBVJt2k3a8/edit#gid=0) open for comment, leave comments at https://github.com/data2health/architecting_attribution/issues/14.

**Comment by LisaOKeefe1** [comment]
@kristiholmes want me to break these into sub tasks or stories? This seems like a big chunk of work and it might be easier to track progress if we do break it down. Let me know. Thanks! :-)

**Comment by kristiholmes** [comment]
All of these bullets are already issues.  Just trying to document better to show context.

**Comment by nicolevasilevsky** [comment]
This is helpful, thanks @kristiholmes!

**Comment by kristiholmes** [comment]
this general plan is a representation of existing issues that are complete or in progress
#38, #39, #14
