### ISSUE TITLE
suggestions for the project description

### ISSUE THREAD

**Issue by mellybelly** [data2health/architecting_attribution#47]
A few comments to potentially make this project repo description more useful to naive readers and to NCATS:

Under the deliverables, I made some suggested descriptors for some, but others i didn't really know what they meant: 
* Better understanding of how to address research output types and versioning of objects in the context of unique identifiers
=> is this the data model and use of Wikidata and other sources as types? perhaps this can be better described if so?
* A large knowledge base of contribution / attribution data available for use by CTSA hubs
=> where will this come from? is it feasible in the 6 month timeframe? where will it live?

Minor- I find the long list of potentially relevant repositories distracting from the actual project. One way to address this would be to create requirements/documentation in the Github Wiki and organize the information there. Similarly, it would be good to start developing some of the implementation requirements and best practices there.

**Comment by kristiholmes** [comment]
done

**Comment by kristiholmes** [comment]
I also updated the RPPR.md file, too.  Thanks again @mellybelly
