### ISSUE TITLE
Make CRO available in Bioportal, Ontobee

### ISSUE THREAD

**Issue by LisaOKeefe1** [data2health/architecting_attribution#49]
As a user I would like this CRO to be available in Bioportal and Ontobee

**Comment by LisaOKeefe1** [comment]
Hi @nicolevasilevsky and @marijane, I am having a hard time recalling who should be assigned this story. If it's not you, please take yourself off. With apologies!

**Comment by nicolevasilevsky** [comment]
@marijane are you working on this?

**Comment by marijane** [comment]
Submitted to BioPortal.
http://bioportal.bioontology.org/ontologies/CRO
It's still processing, so it may take a few hours for it to show up.

Ontobee picked us up automatically, it seems:
http://www.ontobee.org/ontology/CRO
