### ISSUE TITLE
Share news that CRO is ready for pilot in RIS

### ISSUE THREAD

**Issue by LisaOKeefe1** [data2health/architecting_attribution#50]
- [x] Write blog post

- [x] Create pointers to where CRO can be found (and in which formats)

**Comment by LisaOKeefe1** [comment]
Per sprint planning on 5/20, @nicolevasilevsky will write blurb. MJ and Lisa will give it a look. 
Who will create pointers? @marijane

**Comment by nicolevasilevsky** [comment]
I think the pointers are just meant to be links to the CRO GitHub repo, and OLS, etc. I'll do this in the blog post.

**Comment by LisaOKeefe1** [comment]
> I think the pointers are just meant to be links to the CRO GitHub repo, and OLS, etc. I'll do this in the blog post.

Yes! I was just afraid of forgetting them :) thanks!

**Comment by nicolevasilevsky** [comment]
here is a draft blog post:
https://docs.google.com/document/d/1-48gzyaceZwgjVfp1ULmbnA3kZ2U-FVq_1Sx8zz1eTo/edit

**Comment by kristiholmes** [comment]
Thanks, Nicole! I made a few edits, see what you think.
@nicolevasilevsky

**Comment by nicolevasilevsky** [comment]
I think this can be closed
