### ISSUE TITLE
CRO: remove "research" descriptor

### ISSUE THREAD

**Issue by kristiholmes** [data2health/architecting_attribution#53]
research conceptualization role
research coordination role
research instrumentation role
research technician role 

http://www.ontobee.org/ontology/catalog/CRO?iri=http://www.w3.org/2002/07/owl%23Class&max=200

**Comment by nicolevasilevsky** [comment]
research conceptualization role was obsoleted in the cro-edit.owl file

**Comment by nicolevasilevsky** [comment]
done on PR https://github.com/data2health/contributor-role-ontology/pull/67
