### ISSUE TITLE
CRO: remove "software" descriptor

### ISSUE THREAD

**Issue by kristiholmes** [data2health/architecting_attribution#54]
software project management role

http://www.ontobee.org/ontology/catalog/CRO?iri=http://www.w3.org/2002/07/owl%23Class&max=200

**Comment by nicolevasilevsky** [comment]
@kristiholmes - you want this to be renamed to project manager role?

Should I move it to a child of contributor role?

**Comment by marijane** [comment]
per discussion in today's meeting, remove "software" from both the label and the definition for this class.
