### ISSUE TITLE
Create data disctionary for the annotation file structure

### ISSUE THREAD

**Issue by kristiholmes** [data2health/architecting_attribution#55]
depends on deciding annotation file structure
- see https://github.com/data2health/architecting_attribution/issues/14

**Comment by marijane** [comment]
This should be part of the website, see #60.

**Comment by kristiholmes** [comment]
Per conversation with @nicolevasilevsky (with @marijane, @LisaOKeefe1, @kristiholmes)  on 9/8/19 this work should be completed by the work that @mbrush has completed.
