### ISSUE TITLE
Write/submit paper to RO meeting for IEEE E-science

### ISSUE THREAD

**Issue by kristiholmes** [data2health/architecting_attribution#58]
Submit paper about COAR resource types into wikidata to RO meeting for IEEE E-science

https://researchobject.github.io/ro2019/submitting 
https://easychair.org/cfp/ro2019

Deadlines have been extended
    2019-07-05 RO2019 submissions due: articles
    2019-07-15 RO2019 submissions due: abstracts for oral presentation
    2019-07-25 RO2019 Notification of acceptance
    2019-09-02 RO2019 submissions due: poster/demo abstracts
    2019-09-24 RO2019 at IEEE eScience 2019

**Comment by kristiholmes** [comment]
Link to work on submission at https://docs.google.com/document/d/1zQe4HMfTWBOZ0Prg-YY12Dqhv3YQR8DL8-Q4d2j-3FQ/edit 

we can submit a regular submission and also something for the unconference portion of the event...

**Comment by nicolevasilevsky** [comment]
@kristiholmes are you working on this? Do you need help?  Are you planning to attend this conference?

**Comment by kristiholmes** [comment]
Hi @nicolevasilevsky, thanks - yes, help would be great.  I could attend if we get a presentation selected. I pasted the Force2019 abstract in the link above for inspiration, but I was thinking that we might want to develop something around the research object types work since that is new and a good fit. Do we want to do a talk (1-2 page submission) or something appropriate to be included in the proceedings?

Info from last year...
submission: https://zenodo.org/record/1312652#.XRszgXt7mgQ 
presentation: https://digitalhub.northwestern.edu/files/fb4aa42b-ffe8-4548-b6cf-2fa6e32a80ac 
event site: http://www.researchobject.org/ro2018/ 
proceedings: http://www.researchobject.org/ro2018/ro2018-proceedings/

**Comment by nicolevasilevsky** [comment]
Sounds good - I will start a draft.

Note, the link to the presentation from last year is not loading for me (https://digitalhub.northwestern.edu/files/fb4aa42b-ffe8-4548-b6cf-2fa6e32a80ac)

**Comment by nicolevasilevsky** [comment]
I think a 1-2 page submission sounds good

**Comment by nicolevasilevsky** [comment]
An initial draft is ready for review:
https://docs.google.com/document/d/1zQe4HMfTWBOZ0Prg-YY12Dqhv3YQR8DL8-Q4d2j-3FQ/edit#

(I reused a lot of existing text from the Force2019 abstract and Matt's really lovely documentation on the [project plan](https://docs.google.com/document/d/100lB0RjDVzJYJX9hQ1pe_OY90xCSA6mhDfK3xYav3Ow/edit#) and [contribution information model](https://docs.google.com/document/d/1EjStFKBz4bhzeXWmQhSJd2hYpENZKu5Fq3fldXOgCJY/edit#))

**Comment by kristiholmes** [comment]
https://zenodo.org/record/3334688#.XTiso1B7mgR 

Currently in review.
