### ISSUE TITLE
finalize the mapping for the research objects

### ISSUE THREAD

**Issue by nicolevasilevsky** [data2health/architecting_attribution#6]
See file [here](https://docs.google.com/spreadsheets/d/1Mw8gK2NUGM8po7GGRtJTShRM2QNFoR19VJrjQuVCDW8/edit#gid=1619162717)

**Comment by nicolevasilevsky** [comment]
Nicole's outstanding action items:
- import files via ROBOT with @marijane _(in progress)_
- [x] need to import OCRE
- [x] import terms from MeSH
- [x] import terms from foaf _(no longer needed, the foaf term is a property, not a class)_
- [x] add IAO term replaced by annotation
- [x] reclassify the terms from the research objects spreadsheet as children of roo (ROO_00000000)
- [x] add source files to Google Drive instead of GitHub (OWL extraction source files directory)

@marijane's action items:
- [ ] MJ to refactor the ontology to rename it (to Research Artifact Ontology, right?)

**Comment by marijane** [comment]
Research Artefacts Ontology!

**Comment by nicolevasilevsky** [comment]
Oh right :)

**Comment by nicolevasilevsky** [comment]
I am going to close this ticket because the next steps are outlined in #19 and I'll create a new ticket for @marijane to refactor the ontology
