### ISSUE TITLE
Add COAR mappings to Wikidata

### ISSUE THREAD

**Issue by marijane** [data2health/architecting_attribution#61]
We finished our mappings (see #43) and we are ready to start adding them to Wikidata.  

We are going to add them using Wikidata's SKOS relationships.  Note in the spreadsheet, not all of the mappings are exact-match.  Take care to use the correct SKOS relationship when adding the mappings.

**Comment by kristiholmes** [comment]
Please see updates to COAR resource types:  https://www.coar-repositories.org/news-media/new-release-of-the-coar-controlled-vocabulary-resource-type/ 

_COAR is pleased to announce the release of the Resource Type Vocabulary, Version 2. This vocabulary, which is now available in 15 languages, provides standardized terms for different types of content contained in a repository. Controlled vocabularies ensure that “everyone is using the same word to mean the same thing” and are key to achieving the COAR vision of a global knowledge commons, based on an interoperable, international network of open repositories. The Resource Type Vocabulary supports discovery of content by allowing readers to confidently search and browse across systems according to the “type” of content they are looking for._

_The Resource Type Vocabulary is one of three vocabularies published to date by COAR. The other two are Access Rights Vocabulary and Version Type Vocabulary. All vocabularies are openly available in SKOS format (using SKOS eXtension for Labels) with concepts identified using URIs, supporting a hierarchical model with multilingual labels. For Resource Type Version 2.0, the Editorial Board has improved and expanded on the initial release of the vocabulary with new concepts and labels based on the community feedback. Mapping of the labels to other ontologies such as info:eu-repo, Bibo Ontology, DCMI, FaBiO Ontology, DataCite and CASRAI dictionary is available and has been updated. In addition, all three COAR Controlled Vocabularies are used in the OpenAIRE 4.0 Metadata Guidelines._

_COAR strongly encourage the repository community to implement these Controlled Vocabularies to support greater interoperability across repositories. COAR has prepared an implementation guide for the vocabularies, aimed at users of DSpace and other platforms to help with the implementation. These resources (and others) can also be found in the COAR’s Repository Toolkit._

_COAR is extremely grateful for the efforts of the international group contributing to the development and translation of the vocabularies, which require continuous revision, update and maintenance as well as significant work to have them adopted into the repository platforms. We extend our thanks again to the COAR Vocabulary Editorial Board for their important contributions._

@marijane @nicolevasilevsky

**Comment by nicolevasilevsky** [comment]
I reviewed the new version and I don't see any additions that aren't already on our list (https://docs.google.com/spreadsheets/d/1Mw8gK2NUGM8po7GGRtJTShRM2QNFoR19VJrjQuVCDW8/edit#gid=323661248)

**Comment by marijane** [comment]
I mapped everything I could to a Wikidata item, and I added some definitions to the Wikidata items that lacked them.
It turns out that only skos:exactMatch can be directly used on items.  The other SKOS relationships are limited to being used as qualifiers for external ID types.  This means mappings identified as close or narrow matches have not been added.

**Comment by nicolevasilevsky** [comment]
Yay, thanks!
