### ISSUE TITLE
Demonstration workflows

### ISSUE THREAD

**Issue by kristiholmes** [data2health/architecting_attribution#62]
Use personas, build use cases. Need something to show by fall CTSA meeting.

-Basic Scientist
-K, T Scholars
-Clinical Research Coordinator
-Center/Program Administrator
-Clinician/Doctor
-Community-engaged Clinical Researcher
-Lay Patient Navigator
-Research Administrator
-Biostatistician
-Data Analyst
-Developer
-Librarian

**Comment by LisaOKeefe1** [comment]
Lisa to work with NV on adding roles to personas, creating some sort of low tech demonstrator.

**Comment by LisaOKeefe1** [comment]
Blocked on getting into open VIVO. Need developer

**Comment by nicolevasilevsky** [comment]
Personas-CRO mapping here: https://docs.google.com/spreadsheets/d/1HDFTxl6IZtxNvvQq_E4AIpCmoSPj1fZEp3WYtaP4LIU/edit#gid=0

**Comment by LisaOKeefe1** [comment]
?Thank you!


Lisa O'Keefe, MLIS
Sr. Program Administrator
Galter Health Sciences Library & Learning Center
Feinberg School of Medicine
Northwestern University
303 E. Chicago Ave.
Chicago, IL 60611

________________________________
